### ISSUE TITLE
ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by vergissberlin** [JustinThorReid/node-red-contrib-fitbit#4]
**Hi Justin** and thank you for the node!

I followed your instructions but on the redirect, I get this error message:
```
ReferenceError: URL is not defined
    at CodeFlow.getToken (/data/node_modules/client-oauth2/src/client-oauth2.js:584:49)
    at /data/node_modules/node-red-contrib-fitbit/fitbit-credentials.js:52:48
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/src/node-red/node_modules/express/lib/middleware/init.js:40:5)
```

My redirect URL is `https://iot.andrelademann.de/fitbit-credentials/auth/callback?code=13f9cdb4c87ffc78f1f4b67e2fd3daf508b9d3ec&state=fe72c5a5.1ac888#_=_`

I have no idea what that means. Do you have?
Kind regards, André

**Comment by JustinThorReid** [comment]
From the first 2 lines of the console when you start node red, what versions of node-red and nodejs are you using?

I have tested with:
Node-RED version: v1.0.6, v1.0.3
Node.js  version: v12.14.0

**Comment by joshua-nord** [comment]
I was seeing this same issue and think I tracked it down. The error will occur when using nodejs older than v10 (in my case v8).

node-red-contrib-fitbit depends on client-oauth2. In version 4.3.0 of that package, a change was made to the Url handling that made it incompatible with nodejs prior to v10 ([use of the URL type](https://github.com/mulesoft/js-client-oauth2/commit/a06db76c6be2f76ceb032ec24de5315cba8c3944#diff-3d45ba58f0bb15fd649233233ae092b2)). Upgrading the installed nodejs version on the machine running node-red seems like the right solution.

Workarounds:
- use version 4.2.5 of the client-oauth2 package OR
- add this line of code to the top of the node-red-contrib-fitbit.js file to define the missing type:
`global.URL = require('url').URL;`

**Comment by Robby73** [comment]
I always get an error after the authorization page.  I think it never completes the authorization.   I get this sort of error... 

Secure Connection Failed

An error occurred during a connection to 192.168.1.209:1880. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

I have tried different call back urls and its almost always the same sort of error.  I really dont understand how all of the Oauth2 requests work, so i am really lost.

node red version is 1.0.3 
and node js 10.19.0

I cant find the file node-red-contrib-fitbit.js to edit it like joshua-nord suggested.
I tried it on a few different node red installations and its always the same problem.  
my client-ouath2 package is version 4.3.3

Any ideas on what I can do to get this set up?
